//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "641ca15c4420429a17dee2a6"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test Testsson",
  "email": "test@mail.com",
  "password": "test"
}

###

// LOGGA IN USER // VID FEL LÖSENORD SÅ SKALL SVARA MED 401
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUCTS
//

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/641ac6edec090037c8a2edb8

###

// SKAPA PRODUKT // UTAN TOKEN SÅ SKALL ANROPET MISSLYCKAS = 401
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 2",
  "description": "Beskrivning av produkt 1",
  "price": 100,
  "lager": 10,
  "category": "641ac63e182f315c00316e2d",
  "token": "1234key1234"
}

###

// HÄMTA ALLA PRODUKTER FÖR EN SPECIFIK KATEGORI
GET http://localhost:3000/api/products/category/641ac63e182f315c00316e2d
###

//
// API ENDPOINTS KATEGORI
// 

// SKAPA KATEGORI, KEY MÅSTE ANGES // UTAN KEY SVARA 401
# @name createCategory
POST http://localhost:3000/api/categories/add
Content-Type: application/json

{
  "name": "Kategori 11",
  "token": "1234key1234"
}

###

# @name getCategories
GET http://localhost:3000/api/categories

###

//
// API ENDPOINTS ORDERS
//

// HÄMTA ALLA ORDERS, KEY MÅSTE ANGES FÖR ATT FÅ TILLGÅNG TILL ORDERS
GET http://localhost:3000/api/orders/all/1234key1234

###

// HÄMTA ALLA ORDER, FEL KEY // SKALL MISSLYCKAS
GET http://localhost:3000/api/orders/all/123

###

// SKAPA ORDER FÖR EN SPECIFIK USER
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "641ca15c4420429a17dee2a6",
      "products": [
    {
      "productId": "641ac6edec090037c8a2edb8",
      "quantity": 3
    },
    {
      "productId": "642022215e8eb5381fcba5f6",
      "quantity": 2
    }
  ]
}

###

// HÄMTA ORDERS FÖR EN USER // SKALL MISSLYCKAS = INGEN KEY  // SVARA MED 401
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "// USER ID FÖR DEN SOM SKA VISA ORDERS"
}
###

// HÄMTA ORDERS FÖR EN USER // SKALL LYCKAS = KEY
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "641ca15c4420429a17dee2a6",
    "token": "1234key1234"
}
###